(add-to-list 'load-path (concat user-emacs-directory "config"))
(add-to-list 'load-path (concat user-emacs-directory "elisp"))
(add-to-list 'load-path (concat user-emacs-directory "config" "/eyecandy"))
(add-to-list 'load-path (concat user-emacs-directory "config" "/languages"))
(add-to-list 'load-path "/usr/share/emacs/site-lisp")

;; (setq package-archives '(("melpa" . "https://stable.melpa.org/packages/")
;;                          ("gnu" . "https://elpa.gnu.org/packages/")))

(setq package-enable-at-startup nil)

;; boostrap straight.el
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq straight-use-package-by-default :t)
(straight-use-package 'use-package)

(require 'my-env)
(require 'my-core)
(require 'my-functions)
(require 'my-eyecandy)
(require 'my-keychain)
(require 'my-dired)
(require 'my-buffers)
(require 'my-tmux-frames)
(require 'my-elisp)
(require 'my-tags)
(require 'my-completion)
(require 'my-projects)
(require 'my-ag)
(require 'my-interaction)
(require 'my-flycheck)
(require 'my-comint)
(require 'my-unbound-keys)
(require 'my-keys)
(require 'my-copy)
(require 'my-gpt)
(require 'my-languages)
(require 'my-shell)
(require 'my-filetypes)
(require 'my-term)
(require 'my-magit)
(require 'my-android)
(require 'my-eshell)
(require 'my-ielm)
(require 'my-package-list)
(require 'my-evil)
(require 'my-help)
(require 'my-god)
(require 'my-sessions)
(require 'my-leader-keys)

(provide 'init)
