(setq user-emacs-directory (getenv "TRAVIS_BUILD_DIR"))
(print (concat "Using emacs directory: " user-emacs-directory))
(add-to-list 'load-path user-emacs-directory)
(require 'init)
(batch-byte-compile)
